env = SConscript("../godot-cpp/SConstruct")
env.Append(CPPPATH=["src/"])

sources = Glob("src/*.cpp")
library = env.SharedLibrary(
    "../artificial-vision/bin/artificial_vision{}{}".format(env["suffix"], env["SHLIBSUFFIX"]),
    source=sources,
)
Default(library)
